development: &dev_db
  adapter: mongodb
  host: staff.mongohq.com
  database: stockery-arduino
  port: 10052
  user: user
  password: user 

test:
  <<: *dev_db
  database: stockery-arduino-test
  port: 10084

production:
  <<: *dev_db
  port: 10093
  database: app1214616
  user: heroku
  password: 0d5b490776402b4ca42a79174e9b5e66
