defaults: &defaults
  host: 127.0.0.1
  port: 27017

development: &development
  <<: *defaults
  host: staff.mongohq.com
  database: stockery-arduino
  port: 10052
  user: user
  password: user 

test:
  <<: *development
  database: stockery-arduino-test
  port: 10084

production:
  <<: *defaults
  uri: <%= ENV['MONGOHQ_URL'] %>
